// Shared reading and navigation labels stay locale-owned.
export const careCopy = {
  zh: {
    phase_dispatched: '已交给请求流', triggerStatic: '路由固定提醒', triggerModelSwitch: '模型路由切换', purposeConversation: '对话', fieldStatus: '测量状态', fieldMeasured: '已测量', fieldUnavailable: '无法测量', fieldDetectorVersion: '检测器版本', fieldLocale: '统计语言',
    metricN: '有效语句数 N', metricK: '命中语句数 K', metricH: '合并命中数 H', metricF: '命中类别数 F', metricJ: '同类最大语句数 J', metricD: '语句命中比例 D', metricR: '每百词命中数 R', fieldWords: '词数', fieldFamilyStatements: '各类命中语句', fieldExclusions: '排除范围', fieldPhrase: '词条', fieldFamily: '类别', fieldStart: '起始位置', fieldEnd: '结束位置', fieldText: '证据文本', fieldCount: '次数', fieldRatio: '比例', fieldSeverity: '程度',
    'pattern_line-repeat': '重复行清理', 'pattern_filler-lines': '填充行清理', 'pattern_line-cycle': '短句循环', 'pattern_prefix-monotony': '行首重复',
    fieldYes: '是', fieldNo: '否', triggerBudget: '负荷与留存状态变化', triggerCompletion: '完成表述检测', decisionMatched: '命中规则', decisionSuppressed: '本次抑制',
    fieldCompletions: '完成表述次数', fieldObservations: '观察次数', fieldWindow: '观察窗口', fieldThreshold: '阈值', fieldScore: '评分', fieldTotal: '总量', fieldPassed: '是否通过', fieldDispatched: '是否已派发', fieldObservation: '观察结果', fieldRequest: '请求记录',
    fieldPurpose: '请求用途', fieldProvider: '提供方', fieldModel: '模型', fieldPhase: '执行阶段', fieldDecision: '判定', fieldRepeats: '重复次数', fieldMatched: '是否命中', fieldCooldown: '冷却状态',
    back: '返回列表', rawRecord: '原始记录', copy: '复制正文', copied: '已复制', copyFailed: '复制失败', fullText: '展开全文', collapseText: '收起全文', exactText: '当时的完整提示',
    sourceList: '查看来源', sourceSearch: '查找来源序号或正文', sourcePage: '来源页', sourcePrev: '上一页来源', sourceNext: '下一页来源', sourceEmpty: '没有匹配的来源',
    jump: '定位消息', jumping: '正在定位…', jumped: '已定位到聊天中的来源', jumpUnavailable: '此记录没有可定位的消息序号',
    jumpCancelled: '定位已取消：会话已切换或有新的定位请求', jumpOpenChat: '请先打开此会话的聊天视图', jumpMissing: '历史已加载，但此事件没有可定位的聊天节点；可能已被检查点替换或仅存在于日志中',
    jumpHidden: '宿主未提供此节点的原生展开入口', jumpUnsettled: '目标尚未完成展开或滚动，请重试',
    evidence: '当时的判定依据', requestRoute: '请求路由与派发', noRoute: '路由未记录', deliveryUnknown: '派发未记录', phaseUnknown: '阶段未记录',
    ruleName: '规则', ruleVersion: '版本', trigger: '触发', metrics: '当时指标', sourceRoute: '来源路由', producer: '发布来源',
    promptCompletion: '完成表述提醒', promptPattern: '输出模式反馈', promptState: '负荷与留存状态', promptLoop: '循环提醒',
    saved: '输入估算减少', increased: '输入估算增加', before: '维护前', after: '维护后', tokens: 'tok', coverageCount: '条原始来源', range: '序号范围',
    selectedSources: '选区来源', coverageSources: '原始覆盖', summaryWork: '摘要调用', replacementFlow: '选区 → 检查点', audit: '记录完整性',
    inputUnits: '完整输入估算', routeSaving: '路由输入降幅', fixedSaving: '固定估算降幅', fieldMore: '更多字段见原始记录',
    sourceUser: '输入消息', sourceAssistant: '回复消息', sourceTool: '工具结果', sourceRequest: '请求记录', sourceSystem: '系统提示', sourceUnknown: '来源记录',
    requestOnly: '请求记录可能没有独立聊天节点；来源消息仍可逐条定位。', excerptLimit: '节选最多 2,000 字符；定位后查看原消息。',
    pageScope: '本页记录', recordCount: '条记录', promptPreview: '查看提示与依据', actionPreview: '查看结果与来源', rewriteEvidence: '改写依据',
  },
  en: {
    phase_dispatched: 'Handed to request stream', triggerStatic: 'Fixed route reminder', triggerModelSwitch: 'Model route changed', purposeConversation: 'Conversation', fieldStatus: 'Measurement status', fieldMeasured: 'Measured', fieldUnavailable: 'Unavailable', fieldDetectorVersion: 'Detector version', fieldLocale: 'Measurement language',
    metricN: 'Effective statements N', metricK: 'Hit statements K', metricH: 'Merged hits H', metricF: 'Hit families F', metricJ: 'Largest family statement count J', metricD: 'Statement hit ratio D', metricR: 'Hits per hundred words R', fieldWords: 'Word count', fieldFamilyStatements: 'Statements by family', fieldExclusions: 'Excluded ranges', fieldPhrase: 'Phrase', fieldFamily: 'Family', fieldStart: 'Start position', fieldEnd: 'End position', fieldText: 'Evidence text', fieldCount: 'Count', fieldRatio: 'Ratio', fieldSeverity: 'Severity',
    'pattern_line-repeat': 'Repeated-line cleanup', 'pattern_filler-lines': 'Filler-line cleanup', 'pattern_line-cycle': 'Short-line cycle', 'pattern_prefix-monotony': 'Repeated line prefix',
    fieldYes: 'Yes', fieldNo: 'No', triggerBudget: 'Load and retention state changed', triggerCompletion: 'Completion wording detected', decisionMatched: 'Rule matched', decisionSuppressed: 'Suppressed this time',
    fieldCompletions: 'Completion count', fieldObservations: 'Observation count', fieldWindow: 'Observation window', fieldThreshold: 'Threshold', fieldScore: 'Score', fieldTotal: 'Total', fieldPassed: 'Passed', fieldDispatched: 'Dispatched', fieldObservation: 'Observation', fieldRequest: 'Request record',
    fieldPurpose: 'Request purpose', fieldProvider: 'Provider', fieldModel: 'Model', fieldPhase: 'Phase', fieldDecision: 'Decision', fieldRepeats: 'Repeat count', fieldMatched: 'Matched', fieldCooldown: 'Cooldown',
    back: 'Back to list', rawRecord: 'Raw record', copy: 'Copy text', copied: 'Copied', copyFailed: 'Copy failed', fullText: 'Read full text', collapseText: 'Collapse text', exactText: 'Exact saved prompt',
    sourceList: 'Browse sources', sourceSearch: 'Find source sequence or text', sourcePage: 'Source page', sourcePrev: 'Previous sources', sourceNext: 'Next sources', sourceEmpty: 'No matching sources',
    jump: 'Locate message', jumping: 'Locating…', jumped: 'Located the source in chat', jumpUnavailable: 'This record has no message sequence to locate',
    jumpCancelled: 'Navigation cancelled: session changed or a new navigation started', jumpOpenChat: 'Open this session’s chat view first', jumpMissing: 'History loaded, but this event has no chat node to locate; it may have been replaced by a checkpoint or exist only in the log',
    jumpHidden: 'The host has no native reveal action for this node', jumpUnsettled: 'The target has not finished expanding or scrolling; retry',
    evidence: 'Evidence at the time', requestRoute: 'Request route and dispatch', noRoute: 'Route not recorded', deliveryUnknown: 'Dispatch not recorded', phaseUnknown: 'Phase not recorded',
    ruleName: 'Rule', ruleVersion: 'Version', trigger: 'Trigger', metrics: 'Recorded metrics', sourceRoute: 'Source route', producer: 'Producer',
    promptCompletion: 'Completion wording reminder', promptPattern: 'Output pattern feedback', promptState: 'Load and retention state', promptLoop: 'Loop reminder',
    saved: 'Input estimate reduced', increased: 'Input estimate increased', before: 'Before', after: 'After', tokens: 'tok', coverageCount: 'original sources', range: 'Sequence range',
    selectedSources: 'Selected sources', coverageSources: 'Original coverage', summaryWork: 'Summary call', replacementFlow: 'Selection → checkpoint', audit: 'Record completeness',
    inputUnits: 'Complete input estimate', routeSaving: 'Route input saving', fixedSaving: 'Fixed estimate saving', fieldMore: 'More fields in the raw record',
    sourceUser: 'Input message', sourceAssistant: 'Response message', sourceTool: 'Tool result', sourceRequest: 'Request record', sourceSystem: 'System prompt', sourceUnknown: 'Source record',
    requestOnly: 'A request may have no separate chat node; its source messages can still be located individually.', excerptLimit: 'Excerpt limited to 2,000 characters; locate the original message to read more.',
    pageScope: 'Records on this page', recordCount: 'records', promptPreview: 'Read prompt and evidence', actionPreview: 'Read result and sources', rewriteEvidence: 'Rewrite evidence',
  },
}
