export const controlCopy = {
  zh: {
    control_notice_evidence: '切换后，通知必须携带切换边界之后的原始事件序号（sourceSeqs）。缺少依据的旧接口通知会被阻止，并记录原因。',
    controlsTitle: '会话规则', controlsIntro: '每条规则的提醒和保护动作分别控制。保存后影响当前会话的后续执行；已交付的历史与正在执行的操作保留。',
    controlsSearch: '搜索规则、注册插件或来源', controlsLoading: '正在读取会话规则', controlsEmpty: '当前会话没有匹配的规则',
    controlsRegistrant: '注册插件', controlsUndeclared: '未声明（旧接口）', controlsRegistration: '注册入口', controlsExecutor: '执行插件',
    controlsSource: '规则来源', controlsPause: '暂停规则', controlsReset: '恢复声明默认值', controlsSelected: '启用偏好',
    controlsEnabled: '当前可执行', controlsSaving: '正在保存', controlsSaved: '已保存', controlsUnavailable: '规则暂不可用', controlsRefresh: '刷新规则',
    'control_reason-enabled': '已启用', 'control_reason-rule-paused': '规则已暂停', 'control_reason-action-disabled': '动作已关闭',
    'control_reason-executor-unavailable': '执行者未提供', 'control_reason-dependency-disabled': '依赖动作未启用',
    'control_reason-storage-unavailable': '存储不可用，自动执行已暂停', 'control_reason-source-unavailable': '来源已卸载',
    control_notice: '提醒', control_notify: '提醒', control_transform: '请求变换', control_abort: '中止输出', control_resume: '自动续接',
    control_clean: '请求循环清理', control_report: '模型状态报告', control_advice: '状态附带建议', control_prune: '自动裁剪',
    control_summary: '自动摘要', control_retry: '自动重试', control_state: '状态报告与建议', control_maintenance: '预算压力维护', control_overflow: '溢出恢复',
    'control_guidance-meaning': '负载与留存值含义', 'control_guidance-capacity': '未知容量不推测', 'control_guidance-continuity': '连续工作与事实核对',
    'control_guidance-handoff': '交接与压缩结果确认', 'control_guidance-automatic': '自动维护说明', 'control_guidance-labels': '状态标签解释',
    'control_guidance-pressure': '高负载建议', 'control_guidance-hesitation': '反复犹豫压缩时的建议',
    'control_stream-line-repeat': '流式行重复', 'control_stream-time-anxiety': '时间焦虑提醒', 'control_stream-context-anxiety': '上下文焦虑提醒',
    'control_loop-line-repeat': '历史行重复', 'control_loop-filler-lines': '历史填充行', 'control_loop-line-cycle': '历史短句轮转',
    'control_loop-prefix-monotony': '历史前缀单调', control_completion: '完成措辞提醒', controlsOpen: '打开会话规则控制',
    runtimeNavigation: '会话规则管理', runtime_rules: '规则开关', runtime_declarations: '声明与模板', runtime_runs: '运行任务', runtime_preview: '请求预览',
    runtimeRefresh: '刷新', runtimeSearch: '搜索声明或任务', runtimeReadOnly: '查看已注册的声明与运行状态。规则由声明文件或贡献插件提供。',
    runtimePreviewIntro: '预览当前会话的下一次请求变换。预览不会执行工具、写入变量、加入任务队列或消耗冷却与生命周期。',
    runtimePreview: '生成预览', runtimePreviewStale: '会话内容或规则状态已变化，请重新生成预览。', runtimeNoDeclarations: '没有匹配的声明', runtimeNoRuns: '没有匹配的任务',
    runtimeDefinition: '完整声明（只读）', runtimeStage: '执行阶段', runtimeSelection: '选择范围', runtimeMatch: '匹配条件', runtimeDepends: '依赖动作', runtimeNone: '无',
    runtimeExecutorRef: '执行者标识', runtimeInputs: '输入参数', runtimeTarget: '目标位置', runtimePatch: '变换操作', runtimeRules: '规则',
    runtimeEntries: '模板条目', runtimeVariables: '变量', runtimeCurrentValue: '当前值', runtimePartials: '命名模板', runtimeExecutors: '已注册执行者', runtimeTool: '工具名',
    runtimeFilter: '任务状态', runtimeAll: '全部', runtimeEvidence: '执行依据', runtimeTime: '创建时间', runtimeResult: '执行结果',
    runtimeCancel: '请求取消', runtimeCancelRequested: '已请求取消', runtimeCancelAck: '取消请求已记录。正在执行的副作用可能已发生，请以最终任务状态为准。',
    runtimeInjected: '注入字符数', runtimeMatches: '匹配与处理记录', runtimeScheduled: '待执行动作', runtimeBefore: '变换前', runtimeAfter: '变换后', runtimeContext: '请求内容',
    runtimeBudget: '注入预算', runtimeEstimatedTokens: '估算注入 token', runtimeTokenLimit: '注入 token 上限', runtimeUnknown: '未知',
    runtimeImpact: '缓存影响估算', runtimeImpactNote: '比较同一路由下的完整公开请求 JSON。供应商的实际序列化与 token 缓存命中率未知；字节前缀仅作估算参考。',
    runtimeCommonPrefix: '未变化前缀字节数', runtimeChangedSuffix: '变动位置后的字节数', runtimeByteDetails: '请求字节比较',
    runtimeNewer: '上一页', runtimeOlder: '下一页',
    'run_queued': '排队中', 'run_waiting-approval': '等待审批', 'run_running': '执行中', 'run_succeeded': '已成功', 'run_failed': '失败', 'run_skipped': '已跳过', 'run_cancelled': '已取消', 'run_unknown': '结果不确定',
    dispatch_reserved: '请求已预留', dispatch_handoff: '正在交接请求', dispatch_unknown: '请求交付状态不确定', dispatch_settled: '请求已交接',
    delivery_pending: '待交付', delivery_delivered: '已交付', delivery_discarded: '已丢弃', delivery_unknown: '交付不确定', delivery_none: '无需交付', 'delivery_not-delivered': '未交付', 'control_set-variable': '写入变量', control_guidance: '行为指导',
    scope_global: '全局', scope_preset: '预设', scope_session: '会话', scope_turn: '轮次',
    'stage_request.assemble': '请求装配', 'stage_output.delta': '流式输出', 'stage_output.complete': '输出完成', 'stage_tool.before-execute': '工具执行前', 'stage_tool.result': '工具结果', 'stage_display.render': '显示渲染',
    control_inject: '注入上下文', control_replace: '替换内容', control_filter: '过滤', control_setVariable: '写入变量', control_tool: '调用工具', control_program: '执行程序', control_job: '后台任务', control_compact: '历史压缩',
    'control_reason-stage-requires-client-or-stream-projection': '此阶段的投影尚未提供', 'control_reason-host-tool-arguments-immutable': '工具参数不支持在此修改',
    'control_reason-compaction-tool-unavailable': '压缩工具未提供', 'control_reason-workbench-storage-unavailable': '运行存储不可用',
  },
  en: {
    control_notice_evidence: 'After an edit, notices must carry original event sequences (sourceSeqs) newer than the edit boundary. Legacy notices without evidence are blocked with a diagnostic.',
    controlsTitle: 'Session rules', controlsIntro: 'Control reminders and protective actions separately. Saved preferences apply to future execution in this session; delivered history and running operations remain.',
    controlsSearch: 'Search rules, registering plugins or sources', controlsLoading: 'Loading session rules', controlsEmpty: 'No matching rules for this session',
    controlsRegistrant: 'Registering plugin', controlsUndeclared: 'Not declared (legacy API)', controlsRegistration: 'Registration entry', controlsExecutor: 'Executing plugin',
    controlsSource: 'Rule source', controlsPause: 'Pause rule', controlsReset: 'Restore declared defaults', controlsSelected: 'Enabled preference',
    controlsEnabled: 'Executable now', controlsSaving: 'Saving', controlsSaved: 'Saved', controlsUnavailable: 'Rules unavailable', controlsRefresh: 'Refresh rules',
    'control_reason-enabled': 'Enabled', 'control_reason-rule-paused': 'Rule paused', 'control_reason-action-disabled': 'Action disabled',
    'control_reason-executor-unavailable': 'Executor unavailable', 'control_reason-dependency-disabled': 'Required action disabled',
    'control_reason-storage-unavailable': 'Storage unavailable; automatic execution paused', 'control_reason-source-unavailable': 'Source unloaded',
    control_notice: 'Reminder', control_notify: 'Reminder', control_transform: 'Request transform', control_abort: 'Stop output', control_resume: 'Resume automatically',
    control_clean: 'Clean request loops', control_report: 'Model state report', control_advice: 'State advice', control_prune: 'Automatic pruning',
    control_summary: 'Automatic summary', control_retry: 'Automatic retry', control_state: 'State report and advice', control_maintenance: 'Budget maintenance', control_overflow: 'Overflow recovery',
    'control_guidance-meaning': 'Load and retention values', 'control_guidance-capacity': 'Unknown capacity', 'control_guidance-continuity': 'Task continuity and fact checks',
    'control_guidance-handoff': 'Handoff and result acknowledgement', 'control_guidance-automatic': 'Automatic maintenance guidance', 'control_guidance-labels': 'State label interpretation',
    'control_guidance-pressure': 'High load advice', 'control_guidance-hesitation': 'Repeated compaction hesitation',
    'control_stream-line-repeat': 'Streaming line repetition', 'control_stream-time-anxiety': 'Time anxiety reminder', 'control_stream-context-anxiety': 'Context anxiety reminder',
    'control_loop-line-repeat': 'Historical line repetition', 'control_loop-filler-lines': 'Historical filler lines', 'control_loop-line-cycle': 'Historical phrase cycles',
    'control_loop-prefix-monotony': 'Historical prefix monotony', control_completion: 'Completion wording reminder', controlsOpen: 'Open session rule controls',
    runtimeNavigation: 'Session rule management', runtime_rules: 'Rule switches', runtime_declarations: 'Declarations & templates', runtime_runs: 'Action runs', runtime_preview: 'Request preview',
    runtimeRefresh: 'Refresh', runtimeSearch: 'Search declarations or runs', runtimeReadOnly: 'Inspect registered declarations and execution state. Rules come from declaration files or contributing plugins.',
    runtimePreviewIntro: 'Preview the next request transformation for this session. Preview does not execute tools, write variables, enqueue jobs, or consume cooldowns and lifetimes.',
    runtimePreview: 'Generate preview', runtimePreviewStale: 'Session context or rule state changed. Generate a new preview.', runtimeNoDeclarations: 'No matching declarations', runtimeNoRuns: 'No matching runs',
    runtimeDefinition: 'Full declaration (read only)', runtimeStage: 'Stage', runtimeSelection: 'Selection', runtimeMatch: 'Match conditions', runtimeDepends: 'Dependencies', runtimeNone: 'None',
    runtimeExecutorRef: 'Executor reference', runtimeInputs: 'Inputs', runtimeTarget: 'Target', runtimePatch: 'Transformation', runtimeRules: 'Rules',
    runtimeEntries: 'Template entries', runtimeVariables: 'Variables', runtimeCurrentValue: 'Current value', runtimePartials: 'Named templates', runtimeExecutors: 'Registered executors', runtimeTool: 'Tool name',
    runtimeFilter: 'Run status', runtimeAll: 'All', runtimeEvidence: 'Execution evidence', runtimeTime: 'Created', runtimeResult: 'Result',
    runtimeCancel: 'Request cancellation', runtimeCancelRequested: 'Cancellation requested', runtimeCancelAck: 'Cancellation request recorded. Running side effects may already have occurred; check the final run state.',
    runtimeInjected: 'Injected characters', runtimeMatches: 'Match and processing records', runtimeScheduled: 'Scheduled actions', runtimeBefore: 'Before', runtimeAfter: 'After', runtimeContext: 'Request context',
    runtimeBudget: 'Injection budget', runtimeEstimatedTokens: 'Estimated injection tokens', runtimeTokenLimit: 'Injection token limit', runtimeUnknown: 'Unknown',
    runtimeImpact: 'Estimated cache impact', runtimeImpactNote: 'Compare complete public request JSON under the same route. Provider serialization and token cache hits are unknown; the byte prefix is an estimate only.',
    runtimeCommonPrefix: 'Unchanged prefix bytes', runtimeChangedSuffix: 'Bytes after the first change', runtimeByteDetails: 'Request byte comparison',
    runtimeNewer: 'Previous page', runtimeOlder: 'Next page',
    'run_queued': 'Queued', 'run_waiting-approval': 'Awaiting approval', 'run_running': 'Running', 'run_succeeded': 'Succeeded', 'run_failed': 'Failed', 'run_skipped': 'Skipped', 'run_cancelled': 'Cancelled', 'run_unknown': 'Unknown outcome',
    dispatch_reserved: 'Request reserved', dispatch_handoff: 'Request handoff', dispatch_unknown: 'Request delivery unconfirmed', dispatch_settled: 'Request handed off',
    delivery_pending: 'Pending delivery', delivery_delivered: 'Delivered', delivery_discarded: 'Discarded', delivery_unknown: 'Delivery unconfirmed', delivery_none: 'No delivery needed', 'delivery_not-delivered': 'Not delivered', 'control_set-variable': 'Set variable', control_guidance: 'Guidance',
    scope_global: 'Global', scope_preset: 'Preset', scope_session: 'Session', scope_turn: 'Turn',
    'stage_request.assemble': 'Request assembly', 'stage_output.delta': 'Output stream', 'stage_output.complete': 'Output complete', 'stage_tool.before-execute': 'Before tool execution', 'stage_tool.result': 'Tool result', 'stage_display.render': 'Display render',
    control_inject: 'Inject context', control_replace: 'Replace content', control_filter: 'Filter', control_setVariable: 'Set variable', control_tool: 'Call tool', control_program: 'Run program', control_job: 'Background job', control_compact: 'Compact history',
    'control_reason-stage-requires-client-or-stream-projection': 'Projection for this stage is not available', 'control_reason-host-tool-arguments-immutable': 'Tool arguments cannot be modified here',
    'control_reason-compaction-tool-unavailable': 'Compaction tool unavailable', 'control_reason-workbench-storage-unavailable': 'Runtime storage unavailable',
  },
}
